#pragma kernel CSMain

RWTexture3D<float> EditTexture;
int3 toolCentre;
int toolRadius;
int toolHeight;

[numthreads(8,8,8)]
void CSMain (int3 id : SV_DispatchThreadID)
{
	if (id.y >= toolCentre.y && id.y < toolCentre.y + toolHeight) {
		int distance2D = sqrt((id.x - toolCentre.x) * (id.x - toolCentre.x) + (id.z - toolCentre.z) * (id.z - toolCentre.z));
		if (distance2D <= toolRadius) {
			EditTexture[id] = 1;
		}
	}
}
